'use client'

import { createContext, useContext, useEffect, useState, useCallback } from 'react'
import { User, Session, AuthError } from '@supabase/supabase-js'
import { supabase } from '@/lib/supabase'
import { Profile } from '@/types/database'
import { clearAllAuthStorage, isRefreshTokenError, checkForAuthRecovery } from '@/lib/auth-utils'

interface AuthContextType {
  user: User | null
  profile: Profile | null
  session: Session | null
  loading: boolean
  isAdmin: boolean
  signIn: (email: string, password: string) => Promise<{ data: unknown; error: AuthError | null }>
  signUp: (email: string, password: string, fullName: string) => Promise<{ data: unknown; error: AuthError | null }>
  signInWithGoogle: () => Promise<{ data: unknown; error: AuthError | null }>
  signOut: () => Promise<void>
  updateProfile: (updates: Partial<Profile>) => Promise<void>
}

const AuthContext = createContext<AuthContextType>({} as AuthContextType)

export const useAuth = () => {
  const context = useContext(AuthContext)
  if (!context) {
    throw new Error('useAuth must be used within an AuthProvider')
  }
  return context
}

export const AuthProvider = ({ children }: { children: React.ReactNode }) => {
  const [user, setUser] = useState<User | null>(null)
  const [profile, setProfile] = useState<Profile | null>(null)
  const [session, setSession] = useState<Session | null>(null)
  const [loading, setLoading] = useState(true)

  const createUserProfile = useCallback(async (user: User) => {
    try {
      console.log('Attempting to create profile for user:', user.id, user.email)
      
      // First check if profile already exists
      const { data: existingProfile, error: checkError } = await supabase
        .from('profiles')
        .select('id')
        .eq('user_id', user.id) // Changed from 'id' to 'user_id'
        .single()

      if (checkError && checkError.code !== 'PGRST116') {
        // Error other than "no rows returned"
        console.error('Error checking existing profile:', checkError)
        return
      }

      if (existingProfile) {
        console.log('Profile already exists for user:', user.id)
        return
      }

      // Create new profile with correct field structure based on actual table schema
      const profileData = {
        user_id: user.id, // Map to user_id field
        display_name: user.user_metadata?.full_name || null,
        full_name: user.user_metadata?.full_name || null,
        avatar_url: user.user_metadata?.avatar_url || null,
        role: 'user' as const, // Explicitly set default role
        // Note: id, created_at, updated_at will be auto-generated by database
      }

      console.log('Creating profile with data:', profileData)

      const { data, error } = await supabase
        .from('profiles')
        .insert(profileData)
        .select()
      
      if (error) {
        console.error('Error creating user profile:', {
          message: error.message,
          details: error.details,
          hint: error.hint,
          code: error.code
        })
      } else {
        console.log('Successfully created user profile:', data)
      }
    } catch (error) {
      console.error('Exception in createUserProfile:', error)
    }
  }, [])

  // Fetch user profile
  const fetchProfile = useCallback(async (userId: string) => {
    try {
      // Validate userId
      if (!userId || typeof userId !== 'string') {
        console.error('Invalid userId provided to fetchProfile:', userId)
        return null
      }
      
      console.log('Fetching profile for user ID:', userId)
      
      const { data, error } = await supabase
        .from('profiles')
        .select('*')
        .eq('user_id', userId) // Changed from 'id' to 'user_id'
        .single()

      if (error) {
        console.error('Error fetching profile:', error)
        
        // If profile doesn't exist, try to create one
        if (error.code === 'PGRST116') { // No rows returned
          console.log('Profile not found, attempting to create one...')
          const user = await supabase.auth.getUser()
          if (user.data.user) {
            await createUserProfile(user.data.user)
            // Try fetching again after creation
            const { data: newData, error: newError } = await supabase
              .from('profiles')
              .select('*')
              .eq('user_id', userId) // Changed from 'id' to 'user_id'
              .single()
            
            if (newError) {
              console.error('Error fetching profile after creation:', newError)
              return null
            }
            return newData as Profile
          }
        }
        return null
      }

      console.log('Profile fetched successfully:', data)
      return data as Profile
    } catch (error) {
      console.error('Exception in fetchProfile:', error)
      setProfile(null)
      return null
    }
  }, [createUserProfile])

  useEffect(() => {
    // Check for emergency auth recovery first
    checkForAuthRecovery();
    
    // Get initial session
    const getInitialSession = async () => {
      try {
        const { data: { session }, error } = await supabase.auth.getSession()
        if (error) {
          console.error('Error getting session:', error)
          // If there's an error getting session, clear any stale tokens
          if (isRefreshTokenError(error)) {
            console.log('Clearing stale auth tokens')
            clearAllAuthStorage()
            await supabase.auth.signOut()
          }
        } else {
          setSession(session)
          setUser(session?.user ?? null)
          
          // Fetch profile if user exists
          if (session?.user?.id) {
            try {
              const profileData = await fetchProfile(session.user.id)
              setProfile(profileData)
            } catch (error) {
              console.error('Error fetching profile in initial session:', error)
              setProfile(null)
            }
          }
        }
      } catch (error) {
        console.error('Error in getInitialSession:', error)
        // Clear potentially corrupted auth state
        setSession(null)
        setUser(null)
        setProfile(null)
      } finally {
        setLoading(false)
      }
    }

    getInitialSession()

    // Listen for auth changes
    const {
      data: { subscription },
    } = supabase.auth.onAuthStateChange(async (event, session) => {
      console.log('Auth state change:', event, session?.user?.email)
      
      // Handle token refresh errors
      if (event === 'TOKEN_REFRESHED' && !session) {
        console.log('Token refresh failed, clearing auth state')
        setSession(null)
        setUser(null)
        setProfile(null)
        setLoading(false)
        return
      }
      
      // Handle different auth events
      if (event === 'SIGNED_OUT') {
        console.log('User signed out, clearing state')
        setSession(null)
        setUser(null)
        setProfile(null)
        setLoading(false)
        return
      }

      // Handle password recovery
      if (event === 'PASSWORD_RECOVERY') {
        console.log('Password recovery event detected')
        setLoading(false)
        return
      }

      // Handle user updates
      if (event === 'USER_UPDATED') {
        console.log('User updated event detected')
      }
      
      setSession(session)
      setUser(session?.user ?? null)
      
      // Fetch profile if user exists
      if (session?.user?.id) {
        try {
          const profileData = await fetchProfile(session.user.id)
          setProfile(profileData)
        } catch (error) {
          console.error('Error fetching profile in auth state change:', error)
          setProfile(null)
        }
      } else {
        setProfile(null)
      }
      
      setLoading(false)

      // Create user profile on sign up/in for new users
      if ((event === 'SIGNED_IN' || event === 'TOKEN_REFRESHED') && session?.user) {
        try {
          // Check if this is a new user (just signed up/in)
          const profileData = await fetchProfile(session.user.id)
          if (!profileData) {
            console.log('Creating user profile for new user:', session.user.email)
            await createUserProfile(session.user)
            // Re-fetch profile after creation
            const newProfileData = await fetchProfile(session.user.id)
            setProfile(newProfileData)
          }
        } catch (error) {
          console.error('Error creating/fetching profile for new user:', error)
          setProfile(null)
        }
      }
    })

    return () => subscription.unsubscribe()
  }, [fetchProfile, createUserProfile])

  const signIn = async (email: string, password: string) => {
    try {
      console.log('Attempting to sign in user:', email)
      
      // Basic validation
      if (!email || !password) {
        throw new Error('Email and password are required')
      }

      const { data, error } = await supabase.auth.signInWithPassword({
        email: email.trim().toLowerCase(),
        password,
      })
      
      if (error) {
        console.error('Sign in error:', error)
        
        // Handle specific error cases
        if (error.message.includes('Invalid login credentials')) {
          throw new Error('Invalid email or password')
        } else if (error.message.includes('Email not confirmed')) {
          throw new Error('Please confirm your email address before signing in')
        } else if (error.message.includes('too many requests')) {
          throw new Error('Too many login attempts. Please try again later')
        }
        
        throw error
      } else {
        console.log('Sign in successful:', data.user?.email)
      }
      
      return { data, error }
    } catch (error) {
      console.error('Sign in exception:', error)
      return { data: null, error: error as AuthError }
    }
  }

  const signUp = async (email: string, password: string, fullName: string) => {
    try {
      console.log('Attempting to sign up user:', email, 'with name:', fullName)
      
      // Basic validation
      if (!email || !password || !fullName) {
        throw new Error('Email, password, and full name are required')
      }

      const { data, error } = await supabase.auth.signUp({
        email: email.trim().toLowerCase(),
        password,
        options: {
          data: {
            full_name: fullName.trim(),
          },
        },
      })
      
      if (error) {
        console.error('Sign up error:', error)
        throw error
      } else {
        console.log('Sign up successful:', data)
        // Note: Profile creation will be handled in the auth state change listener
      }
      
      return { data, error }
    } catch (error) {
      console.error('Sign up exception:', error)
      return { data: null, error: error as AuthError }
    }
  }

  const signInWithGoogle = async () => {
    try {
      console.log('Attempting to sign in with Google')
      
      // Get the current URL origin for proper redirect
      const origin = typeof window !== 'undefined' ? window.location.origin : ''
      const redirectTo = `${origin}/auth/callback`
      
      console.log('OAuth redirect URL:', redirectTo)
      
      const { data, error } = await supabase.auth.signInWithOAuth({
        provider: 'google',
        options: {
          redirectTo,
          queryParams: {
            access_type: 'offline',
            prompt: 'consent',
          },
        },
      })
      
      if (error) {
        console.error('Google sign in error:', error)
        throw error
      } else {
        console.log('Google OAuth initiated successfully:', data)
      }
      
      return { data, error }
    } catch (error) {
      console.error('Google sign in exception:', error)
      return { data: null, error: error as AuthError }
    }
  }

  const signOut = async () => {
    try {
      console.log('Signing out user')
      
      // Always clear local state first to prevent UI glitches
      setSession(null)
      setUser(null)
      setProfile(null)
      
      // Check if we have a session before attempting to sign out
      const { data: { session } } = await supabase.auth.getSession()
      
      if (!session) {
        console.log('No active session found, clearing local storage')
        // Clear any stale tokens from localStorage
        clearAllAuthStorage()
        return
      }
      
      const { error } = await supabase.auth.signOut()
      if (error) {
        console.error('Sign out error:', error)
        // Clear localStorage even if signOut fails
        clearAllAuthStorage()
        
        // Don't throw error, just log it - user state is already cleared
        if (isRefreshTokenError(error)) {
          console.log('Refresh token was already invalid, sign out completed locally')
        }
      } else {
        console.log('Sign out successful')
      }
    } catch (error) {
      console.error('Sign out exception:', error)
      // Always ensure local state is cleared and localStorage is cleaned
      setSession(null)
      setUser(null)
      setProfile(null)
      clearAllAuthStorage()
    }
  }

  const updateProfile = async (updates: Partial<Profile>) => {
    if (!user?.id) throw new Error('No user logged in')
    
    const { error } = await supabase
      .from('profiles')
      .update(updates)
      .eq('user_id', user.id) // Changed from 'id' to 'user_id'

    if (error) throw error

    // Refresh profile
    const updatedProfile = await fetchProfile(user.id)
    setProfile(updatedProfile)
  }

  const isAdmin = profile?.role === 'admin'

  const value = {
    user,
    profile,
    session,
    loading,
    isAdmin,
    signIn,
    signUp,
    signInWithGoogle,
    signOut,
    updateProfile,
  }

  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>
}
